name: google_maps_polygon
description: "A Flutter package for drawing polygons on Google Maps on Web"
version: 0.0.1

repository: https://github.com/Wajeeh007/google_maps_polygon.git
issue_tracker: https://github.com/Wajeeh007/google_maps_polygon/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
